name = "duhby's tmc"
author = "duhby"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "244a681670d1facf789fc49bb2e27672aca765d8e9756c5e72974a7592fd0bce"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
