name = "duhby's tmc"
author = "duhby"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "706ecad9fdb5a0c7adad9bd4fdcf0d65bf299e771605c6016c5ee8edd0af00ff"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
