name = "duhby's tmc"
author = "duhby"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cebd261b121c7e39fa34a74a2f446678937e4173d33891ac19d4f0b90c37c52"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
